// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 * ApmServer represents an APM Server resource in a Kubernetes cluster.
 *
 * @schema ApmServer
 */
export class ApmServer extends ApiObject {
  /**
   * Returns the apiVersion and kind for "ApmServer"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'apm.k8s.elastic.co/v1',
    kind: 'ApmServer',
  }

  /**
   * Renders a Kubernetes manifest for "ApmServer".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ApmServerProps = {}): any {
    return {
      ...ApmServer.GVK,
      ...toJson_ApmServerProps(props),
    };
  }

  /**
   * Defines a "ApmServer" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ApmServerProps = {}) {
    super(scope, id, {
      ...ApmServer.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...ApmServer.GVK,
      ...toJson_ApmServerProps(resolved),
    };
  }
}

/**
 * ApmServer represents an APM Server resource in a Kubernetes cluster.
 *
 * @schema ApmServer
 */
export interface ApmServerProps {
  /**
   * @schema ApmServer#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * ApmServerSpec holds the specification of an APM Server.
   *
   * @schema ApmServer#spec
   */
  readonly spec?: ApmServerSpec;

}

/**
 * Converts an object of type 'ApmServerProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerProps(obj: ApmServerProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_ApmServerSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * ApmServerSpec holds the specification of an APM Server.
 *
 * @schema ApmServerSpec
 */
export interface ApmServerSpec {
  /**
   * Config holds the APM Server configuration. See: https://www.elastic.co/guide/en/apm/server/current/configuring-howto-apm-server.html
   *
   * @schema ApmServerSpec#config
   */
  readonly config?: any;

  /**
   * Count of APM Server instances to deploy.
   *
   * @schema ApmServerSpec#count
   */
  readonly count?: number;

  /**
   * ElasticsearchRef is a reference to the output Elasticsearch cluster running in the same Kubernetes cluster.
   *
   * @schema ApmServerSpec#elasticsearchRef
   */
  readonly elasticsearchRef?: ApmServerSpecElasticsearchRef;

  /**
   * HTTP holds the HTTP layer configuration for the APM Server resource.
   *
   * @schema ApmServerSpec#http
   */
  readonly http?: ApmServerSpecHttp;

  /**
   * Image is the APM Server Docker image to deploy.
   *
   * @schema ApmServerSpec#image
   */
  readonly image?: string;

  /**
   * PodTemplate provides customisation options (labels, annotations, affinity rules, resource requests, and so on) for the APM Server pods.
   *
   * @schema ApmServerSpec#podTemplate
   */
  readonly podTemplate?: any;

  /**
   * SecureSettings is a list of references to Kubernetes secrets containing sensitive configuration options for APM Server.
   *
   * @schema ApmServerSpec#secureSettings
   */
  readonly secureSettings?: ApmServerSpecSecureSettings[];

  /**
   * ServiceAccountName is used to check access from the current resource to a resource (eg. Elasticsearch) in a different namespace. Can only be used if ECK is enforcing RBAC on references.
   *
   * @schema ApmServerSpec#serviceAccountName
   */
  readonly serviceAccountName?: string;

  /**
   * Version of the APM Server.
   *
   * @schema ApmServerSpec#version
   */
  readonly version: string;

}

/**
 * Converts an object of type 'ApmServerSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpec(obj: ApmServerSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'config': obj.config,
    'count': obj.count,
    'elasticsearchRef': toJson_ApmServerSpecElasticsearchRef(obj.elasticsearchRef),
    'http': toJson_ApmServerSpecHttp(obj.http),
    'image': obj.image,
    'podTemplate': obj.podTemplate,
    'secureSettings': obj.secureSettings?.map(y => toJson_ApmServerSpecSecureSettings(y)),
    'serviceAccountName': obj.serviceAccountName,
    'version': obj.version,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * ElasticsearchRef is a reference to the output Elasticsearch cluster running in the same Kubernetes cluster.
 *
 * @schema ApmServerSpecElasticsearchRef
 */
export interface ApmServerSpecElasticsearchRef {
  /**
   * Name of the Kubernetes object.
   *
   * @schema ApmServerSpecElasticsearchRef#name
   */
  readonly name: string;

  /**
   * Namespace of the Kubernetes object. If empty, defaults to the current namespace.
   *
   * @schema ApmServerSpecElasticsearchRef#namespace
   */
  readonly namespace?: string;

}

/**
 * Converts an object of type 'ApmServerSpecElasticsearchRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpecElasticsearchRef(obj: ApmServerSpecElasticsearchRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * HTTP holds the HTTP layer configuration for the APM Server resource.
 *
 * @schema ApmServerSpecHttp
 */
export interface ApmServerSpecHttp {
  /**
   * Service defines the template for the associated Kubernetes Service object.
   *
   * @schema ApmServerSpecHttp#service
   */
  readonly service?: ApmServerSpecHttpService;

  /**
   * TLS defines options for configuring TLS for HTTP.
   *
   * @schema ApmServerSpecHttp#tls
   */
  readonly tls?: ApmServerSpecHttpTls;

}

/**
 * Converts an object of type 'ApmServerSpecHttp' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpecHttp(obj: ApmServerSpecHttp | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'service': toJson_ApmServerSpecHttpService(obj.service),
    'tls': toJson_ApmServerSpecHttpTls(obj.tls),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * SecretSource defines a data source based on a Kubernetes Secret.
 *
 * @schema ApmServerSpecSecureSettings
 */
export interface ApmServerSpecSecureSettings {
  /**
   * Entries define how to project each key-value pair in the secret to filesystem paths. If not defined, all keys will be projected to similarly named paths in the filesystem. If defined, only the specified keys will be projected to the corresponding paths.
   *
   * @schema ApmServerSpecSecureSettings#entries
   */
  readonly entries?: ApmServerSpecSecureSettingsEntries[];

  /**
   * SecretName is the name of the secret.
   *
   * @schema ApmServerSpecSecureSettings#secretName
   */
  readonly secretName: string;

}

/**
 * Converts an object of type 'ApmServerSpecSecureSettings' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpecSecureSettings(obj: ApmServerSpecSecureSettings | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'entries': obj.entries?.map(y => toJson_ApmServerSpecSecureSettingsEntries(y)),
    'secretName': obj.secretName,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Service defines the template for the associated Kubernetes Service object.
 *
 * @schema ApmServerSpecHttpService
 */
export interface ApmServerSpecHttpService {
  /**
   * ObjectMeta is the metadata of the service. The name and namespace provided here are managed by ECK and will be ignored.
   *
   * @schema ApmServerSpecHttpService#metadata
   */
  readonly metadata?: any;

  /**
   * Spec is the specification of the service.
   *
   * @schema ApmServerSpecHttpService#spec
   */
  readonly spec?: ApmServerSpecHttpServiceSpec;

}

/**
 * Converts an object of type 'ApmServerSpecHttpService' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpecHttpService(obj: ApmServerSpecHttpService | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_ApmServerSpecHttpServiceSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * TLS defines options for configuring TLS for HTTP.
 *
 * @schema ApmServerSpecHttpTls
 */
export interface ApmServerSpecHttpTls {
  /**
   * Certificate is a reference to a Kubernetes secret that contains the certificate and private key for enabling TLS. The referenced secret should contain the following:
   * - `ca.crt`: The certificate authority (optional). - `tls.crt`: The certificate (or a chain). - `tls.key`: The private key to the first certificate in the certificate chain.
   *
   * @schema ApmServerSpecHttpTls#certificate
   */
  readonly certificate?: ApmServerSpecHttpTlsCertificate;

  /**
   * SelfSignedCertificate allows configuring the self-signed certificate generated by the operator.
   *
   * @schema ApmServerSpecHttpTls#selfSignedCertificate
   */
  readonly selfSignedCertificate?: ApmServerSpecHttpTlsSelfSignedCertificate;

}

/**
 * Converts an object of type 'ApmServerSpecHttpTls' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpecHttpTls(obj: ApmServerSpecHttpTls | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'certificate': toJson_ApmServerSpecHttpTlsCertificate(obj.certificate),
    'selfSignedCertificate': toJson_ApmServerSpecHttpTlsSelfSignedCertificate(obj.selfSignedCertificate),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * KeyToPath defines how to map a key in a Secret object to a filesystem path.
 *
 * @schema ApmServerSpecSecureSettingsEntries
 */
export interface ApmServerSpecSecureSettingsEntries {
  /**
   * Key is the key contained in the secret.
   *
   * @schema ApmServerSpecSecureSettingsEntries#key
   */
  readonly key: string;

  /**
   * Path is the relative file path to map the key to. Path must not be an absolute file path and must not contain any ".." components.
   *
   * @schema ApmServerSpecSecureSettingsEntries#path
   */
  readonly path?: string;

}

/**
 * Converts an object of type 'ApmServerSpecSecureSettingsEntries' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpecSecureSettingsEntries(obj: ApmServerSpecSecureSettingsEntries | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'path': obj.path,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Spec is the specification of the service.
 *
 * @schema ApmServerSpecHttpServiceSpec
 */
export interface ApmServerSpecHttpServiceSpec {
  /**
   * clusterIP is the IP address of the service and is usually assigned randomly by the master. If an address is specified manually and is not in use by others, it will be allocated to the service; otherwise, creation of the service will fail. This field can not be changed through updates. Valid values are "None", empty string (""), or a valid IP address. "None" can be specified for headless services when proxying is not required. Only applies to types ClusterIP, NodePort, and LoadBalancer. Ignored if type is ExternalName. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
   *
   * @schema ApmServerSpecHttpServiceSpec#clusterIP
   */
  readonly clusterIp?: string;

  /**
   * externalIPs is a list of IP addresses for which nodes in the cluster will also accept traffic for this service.  These IPs are not managed by Kubernetes.  The user is responsible for ensuring that traffic arrives at a node with this IP.  A common example is external load-balancers that are not part of the Kubernetes system.
   *
   * @schema ApmServerSpecHttpServiceSpec#externalIPs
   */
  readonly externalIPs?: string[];

  /**
   * externalName is the external reference that kubedns or equivalent will return as a CNAME record for this service. No proxying will be involved. Must be a valid RFC-1123 hostname (https://tools.ietf.org/html/rfc1123) and requires Type to be ExternalName.
   *
   * @schema ApmServerSpecHttpServiceSpec#externalName
   */
  readonly externalName?: string;

  /**
   * externalTrafficPolicy denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints. "Local" preserves the client source IP and avoids a second hop for LoadBalancer and Nodeport type services, but risks potentially imbalanced traffic spreading. "Cluster" obscures the client source IP and may cause a second hop to another node, but should have good overall load-spreading.
   *
   * @schema ApmServerSpecHttpServiceSpec#externalTrafficPolicy
   */
  readonly externalTrafficPolicy?: string;

  /**
   * healthCheckNodePort specifies the healthcheck nodePort for the service. If not specified, HealthCheckNodePort is created by the service api backend with the allocated nodePort. Will use user-specified nodePort value if specified by the client. Only effects when Type is set to LoadBalancer and ExternalTrafficPolicy is set to Local.
   *
   * @schema ApmServerSpecHttpServiceSpec#healthCheckNodePort
   */
  readonly healthCheckNodePort?: number;

  /**
   * ipFamily specifies whether this Service has a preference for a particular IP family (e.g. IPv4 vs. IPv6).  If a specific IP family is requested, the clusterIP field will be allocated from that family, if it is available in the cluster.  If no IP family is requested, the cluster's primary IP family will be used. Other IP fields (loadBalancerIP, loadBalancerSourceRanges, externalIPs) and controllers which allocate external load-balancers should use the same IP family.  Endpoints for this Service will be of this family.  This field is immutable after creation. Assigning a ServiceIPFamily not available in the cluster (e.g. IPv6 in IPv4 only cluster) is an error condition and will fail during clusterIP assignment.
   *
   * @schema ApmServerSpecHttpServiceSpec#ipFamily
   */
  readonly ipFamily?: string;

  /**
   * Only applies to Service Type: LoadBalancer LoadBalancer will get created with the IP specified in this field. This feature depends on whether the underlying cloud-provider supports specifying the loadBalancerIP when a load balancer is created. This field will be ignored if the cloud-provider does not support the feature.
   *
   * @schema ApmServerSpecHttpServiceSpec#loadBalancerIP
   */
  readonly loadBalancerIp?: string;

  /**
   * If specified and supported by the platform, this will restrict traffic through the cloud-provider load-balancer will be restricted to the specified client IPs. This field will be ignored if the cloud-provider does not support the feature." More info: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/
   *
   * @schema ApmServerSpecHttpServiceSpec#loadBalancerSourceRanges
   */
  readonly loadBalancerSourceRanges?: string[];

  /**
   * The list of ports that are exposed by this service. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
   *
   * @schema ApmServerSpecHttpServiceSpec#ports
   */
  readonly ports?: ApmServerSpecHttpServiceSpecPorts[];

  /**
   * publishNotReadyAddresses, when set to true, indicates that DNS implementations must publish the notReadyAddresses of subsets for the Endpoints associated with the Service. The default value is false. The primary use case for setting this field is to use a StatefulSet's Headless Service to propagate SRV records for its Pods without respect to their readiness for purpose of peer discovery.
   *
   * @schema ApmServerSpecHttpServiceSpec#publishNotReadyAddresses
   */
  readonly publishNotReadyAddresses?: boolean;

  /**
   * Route service traffic to pods with label keys and values matching this selector. If empty or not present, the service is assumed to have an external process managing its endpoints, which Kubernetes will not modify. Only applies to types ClusterIP, NodePort, and LoadBalancer. Ignored if type is ExternalName. More info: https://kubernetes.io/docs/concepts/services-networking/service/
   *
   * @schema ApmServerSpecHttpServiceSpec#selector
   */
  readonly selector?: { [key: string]: string };

  /**
   * Supports "ClientIP" and "None". Used to maintain session affinity. Enable client IP based session affinity. Must be ClientIP or None. Defaults to None. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
   *
   * @default None. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
   * @schema ApmServerSpecHttpServiceSpec#sessionAffinity
   */
  readonly sessionAffinity?: string;

  /**
   * sessionAffinityConfig contains the configurations of session affinity.
   *
   * @schema ApmServerSpecHttpServiceSpec#sessionAffinityConfig
   */
  readonly sessionAffinityConfig?: ApmServerSpecHttpServiceSpecSessionAffinityConfig;

  /**
   * topologyKeys is a preference-order list of topology keys which implementations of services should use to preferentially sort endpoints when accessing this Service, it can not be used at the same time as externalTrafficPolicy=Local. Topology keys must be valid label keys and at most 16 keys may be specified. Endpoints are chosen based on the first topology key with available backends. If this field is specified and all entries have no backends that match the topology of the client, the service has no backends for that client and connections should fail. The special value "*" may be used to mean "any topology". This catch-all value, if used, only makes sense as the last value in the list. If this is not specified or empty, no topology constraints will be applied.
   *
   * @schema ApmServerSpecHttpServiceSpec#topologyKeys
   */
  readonly topologyKeys?: string[];

  /**
   * type determines how the Service is exposed. Defaults to ClusterIP. Valid options are ExternalName, ClusterIP, NodePort, and LoadBalancer. "ExternalName" maps to the specified externalName. "ClusterIP" allocates a cluster-internal IP address for load-balancing to endpoints. Endpoints are determined by the selector or if that is not specified, by manual construction of an Endpoints object. If clusterIP is "None", no virtual IP is allocated and the endpoints are published as a set of endpoints rather than a stable IP. "NodePort" builds on ClusterIP and allocates a port on every node which routes to the clusterIP. "LoadBalancer" builds on NodePort and creates an external load-balancer (if supported in the current cloud) which routes to the clusterIP. More info: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
   *
   * @default ClusterIP. Valid options are ExternalName, ClusterIP, NodePort, and LoadBalancer. "ExternalName" maps to the specified externalName. "ClusterIP" allocates a cluster-internal IP address for load-balancing to endpoints. Endpoints are determined by the selector or if that is not specified, by manual construction of an Endpoints object. If clusterIP is "None", no virtual IP is allocated and the endpoints are published as a set of endpoints rather than a stable IP. "NodePort" builds on ClusterIP and allocates a port on every node which routes to the clusterIP. "LoadBalancer" builds on NodePort and creates an external load-balancer (if supported in the current cloud) which routes to the clusterIP. More info: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
   * @schema ApmServerSpecHttpServiceSpec#type
   */
  readonly type?: string;

}

/**
 * Converts an object of type 'ApmServerSpecHttpServiceSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpecHttpServiceSpec(obj: ApmServerSpecHttpServiceSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'clusterIP': obj.clusterIp,
    'externalIPs': obj.externalIPs?.map(y => y),
    'externalName': obj.externalName,
    'externalTrafficPolicy': obj.externalTrafficPolicy,
    'healthCheckNodePort': obj.healthCheckNodePort,
    'ipFamily': obj.ipFamily,
    'loadBalancerIP': obj.loadBalancerIp,
    'loadBalancerSourceRanges': obj.loadBalancerSourceRanges?.map(y => y),
    'ports': obj.ports?.map(y => toJson_ApmServerSpecHttpServiceSpecPorts(y)),
    'publishNotReadyAddresses': obj.publishNotReadyAddresses,
    'selector': ((obj.selector) === undefined) ? undefined : (Object.entries(obj.selector).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'sessionAffinity': obj.sessionAffinity,
    'sessionAffinityConfig': toJson_ApmServerSpecHttpServiceSpecSessionAffinityConfig(obj.sessionAffinityConfig),
    'topologyKeys': obj.topologyKeys?.map(y => y),
    'type': obj.type,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Certificate is a reference to a Kubernetes secret that contains the certificate and private key for enabling TLS. The referenced secret should contain the following:
 * - `ca.crt`: The certificate authority (optional). - `tls.crt`: The certificate (or a chain). - `tls.key`: The private key to the first certificate in the certificate chain.
 *
 * @schema ApmServerSpecHttpTlsCertificate
 */
export interface ApmServerSpecHttpTlsCertificate {
  /**
   * SecretName is the name of the secret.
   *
   * @schema ApmServerSpecHttpTlsCertificate#secretName
   */
  readonly secretName?: string;

}

/**
 * Converts an object of type 'ApmServerSpecHttpTlsCertificate' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpecHttpTlsCertificate(obj: ApmServerSpecHttpTlsCertificate | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'secretName': obj.secretName,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * SelfSignedCertificate allows configuring the self-signed certificate generated by the operator.
 *
 * @schema ApmServerSpecHttpTlsSelfSignedCertificate
 */
export interface ApmServerSpecHttpTlsSelfSignedCertificate {
  /**
   * Disabled indicates that the provisioning of the self-signed certifcate should be disabled.
   *
   * @schema ApmServerSpecHttpTlsSelfSignedCertificate#disabled
   */
  readonly disabled?: boolean;

  /**
   * SubjectAlternativeNames is a list of SANs to include in the generated HTTP TLS certificate.
   *
   * @schema ApmServerSpecHttpTlsSelfSignedCertificate#subjectAltNames
   */
  readonly subjectAltNames?: ApmServerSpecHttpTlsSelfSignedCertificateSubjectAltNames[];

}

/**
 * Converts an object of type 'ApmServerSpecHttpTlsSelfSignedCertificate' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpecHttpTlsSelfSignedCertificate(obj: ApmServerSpecHttpTlsSelfSignedCertificate | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'disabled': obj.disabled,
    'subjectAltNames': obj.subjectAltNames?.map(y => toJson_ApmServerSpecHttpTlsSelfSignedCertificateSubjectAltNames(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * ServicePort contains information on service's port.
 *
 * @schema ApmServerSpecHttpServiceSpecPorts
 */
export interface ApmServerSpecHttpServiceSpecPorts {
  /**
   * The name of this port within the service. This must be a DNS_LABEL. All ports within a ServiceSpec must have unique names. When considering the endpoints for a Service, this must match the 'name' field in the EndpointPort. Optional if only one ServicePort is defined on this service.
   *
   * @schema ApmServerSpecHttpServiceSpecPorts#name
   */
  readonly name?: string;

  /**
   * The port on each node on which this service is exposed when type=NodePort or LoadBalancer. Usually assigned by the system. If specified, it will be allocated to the service if unused or else creation of the service will fail. Default is to auto-allocate a port if the ServiceType of this Service requires one. More info: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
   *
   * @default to auto-allocate a port if the ServiceType of this Service requires one. More info: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
   * @schema ApmServerSpecHttpServiceSpecPorts#nodePort
   */
  readonly nodePort?: number;

  /**
   * The port that will be exposed by this service.
   *
   * @schema ApmServerSpecHttpServiceSpecPorts#port
   */
  readonly port: number;

  /**
   * The IP protocol for this port. Supports "TCP", "UDP", and "SCTP". Default is TCP.
   *
   * @default TCP.
   * @schema ApmServerSpecHttpServiceSpecPorts#protocol
   */
  readonly protocol?: string;

  /**
   * Number or name of the port to access on the pods targeted by the service. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME. If this is a string, it will be looked up as a named port in the target Pod's container ports. If this is not specified, the value of the 'port' field is used (an identity map). This field is ignored for services with clusterIP=None, and should be omitted or set equal to the 'port' field. More info: https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
   *
   * @schema ApmServerSpecHttpServiceSpecPorts#targetPort
   */
  readonly targetPort?: ApmServerSpecHttpServiceSpecPortsTargetPort;

}

/**
 * Converts an object of type 'ApmServerSpecHttpServiceSpecPorts' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpecHttpServiceSpecPorts(obj: ApmServerSpecHttpServiceSpecPorts | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'nodePort': obj.nodePort,
    'port': obj.port,
    'protocol': obj.protocol,
    'targetPort': obj.targetPort?.value,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * sessionAffinityConfig contains the configurations of session affinity.
 *
 * @schema ApmServerSpecHttpServiceSpecSessionAffinityConfig
 */
export interface ApmServerSpecHttpServiceSpecSessionAffinityConfig {
  /**
   * clientIP contains the configurations of Client IP based session affinity.
   *
   * @schema ApmServerSpecHttpServiceSpecSessionAffinityConfig#clientIP
   */
  readonly clientIp?: ApmServerSpecHttpServiceSpecSessionAffinityConfigClientIp;

}

/**
 * Converts an object of type 'ApmServerSpecHttpServiceSpecSessionAffinityConfig' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpecHttpServiceSpecSessionAffinityConfig(obj: ApmServerSpecHttpServiceSpecSessionAffinityConfig | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'clientIP': toJson_ApmServerSpecHttpServiceSpecSessionAffinityConfigClientIp(obj.clientIp),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * SubjectAlternativeName represents a SAN entry in a x509 certificate.
 *
 * @schema ApmServerSpecHttpTlsSelfSignedCertificateSubjectAltNames
 */
export interface ApmServerSpecHttpTlsSelfSignedCertificateSubjectAltNames {
  /**
   * DNS is the DNS name of the subject.
   *
   * @schema ApmServerSpecHttpTlsSelfSignedCertificateSubjectAltNames#dns
   */
  readonly dns?: string;

  /**
   * IP is the IP address of the subject.
   *
   * @schema ApmServerSpecHttpTlsSelfSignedCertificateSubjectAltNames#ip
   */
  readonly ip?: string;

}

/**
 * Converts an object of type 'ApmServerSpecHttpTlsSelfSignedCertificateSubjectAltNames' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpecHttpTlsSelfSignedCertificateSubjectAltNames(obj: ApmServerSpecHttpTlsSelfSignedCertificateSubjectAltNames | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'dns': obj.dns,
    'ip': obj.ip,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Number or name of the port to access on the pods targeted by the service. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME. If this is a string, it will be looked up as a named port in the target Pod's container ports. If this is not specified, the value of the 'port' field is used (an identity map). This field is ignored for services with clusterIP=None, and should be omitted or set equal to the 'port' field. More info: https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
 *
 * @schema ApmServerSpecHttpServiceSpecPortsTargetPort
 */
export class ApmServerSpecHttpServiceSpecPortsTargetPort {
  public static fromNumber(value: number): ApmServerSpecHttpServiceSpecPortsTargetPort {
    return new ApmServerSpecHttpServiceSpecPortsTargetPort(value);
  }
  public static fromString(value: string): ApmServerSpecHttpServiceSpecPortsTargetPort {
    return new ApmServerSpecHttpServiceSpecPortsTargetPort(value);
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * clientIP contains the configurations of Client IP based session affinity.
 *
 * @schema ApmServerSpecHttpServiceSpecSessionAffinityConfigClientIp
 */
export interface ApmServerSpecHttpServiceSpecSessionAffinityConfigClientIp {
  /**
   * timeoutSeconds specifies the seconds of ClientIP type session sticky time. The value must be >0 && <=86400(for 1 day) if ServiceAffinity == "ClientIP". Default value is 10800(for 3 hours).
   *
   * @schema ApmServerSpecHttpServiceSpecSessionAffinityConfigClientIp#timeoutSeconds
   */
  readonly timeoutSeconds?: number;

}

/**
 * Converts an object of type 'ApmServerSpecHttpServiceSpecSessionAffinityConfigClientIp' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApmServerSpecHttpServiceSpecSessionAffinityConfigClientIp(obj: ApmServerSpecHttpServiceSpecSessionAffinityConfigClientIp | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'timeoutSeconds': obj.timeoutSeconds,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

